choshop/blog/urls.py
from django.urls import path
from . import views 
app_name = 'blog'
urlpatterns = [
	path('detail',views.detail ,name='post_detail'),
	path('list',views.list_posts ,name='list_posts'),

]

choshop/choshop/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

from django.views.decorators.csrf import csrf_protect, csrf_exempt
from graphene_django.views import GraphQLView
urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    # added 
    path('account/', include('django.contrib.auth.urls')),
    path('blog/', include('blog.urls')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('', include('shop.urls')),
    path('orders', include('orders.urls')),
    path('markers', include('markers.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),

    path('graphql/', csrf_exempt(GraphQLView.as_view(graphiql=True))),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

choshop/markers/urls.py
from django.urls import path

from .views import MarkersMapView
from . import views 
app_name = "markers"

urlpatterns = [
    path("map/", MarkersMapView.as_view()),
    path('address/', views.AddressListView.as_view(), name='address_list'),
    path('address/create', views.AddressCreateView.as_view(), name='address_create'),    path(
       "address/<int:pk>/",
       views.AddressUpdateView.as_view(),
       name="address_update",
    ),
    path(
       "address/<int:pk>/delete/",
       views.AddressDeleteView.as_view(),
       name="address_delete",
    ),
]

choshop/markers/models.py
# Create your models here.
#from django.contrib.gis.db.models import PointField
from django.db import models
from account.models import Account

class Marker(models.Model):
	"""A marker with name and location."""

	name = models.CharField(max_length=255)


class Address(models.Model):
	 SUPPORTED_COUNTRIES = (
		("ir", "ایران"),
		("us", "ایالات متحده آمریکا")
	)
	
	account = models.ForeignKey(Account, on_delete=models.CASCADE)
	name = models.CharField(max_length=60)
	address1 = models.CharField("Address line 1", max_length=60)
	address2 = models.CharField(
		"Address line 2", max_length=60, blank=True
	)
	zip_code = models.CharField(
		"ادرس پستی", max_length=12
	)
	city = models.CharField(max_length=60)
	country = models.CharField(
		max_length=3, choices=SUPPORTED_COUNTRIES
	)
	def __str__(self):
		return ", ".join(
			[
				 self.name,
				 self.address1,
				 self.address2,
				 self.zip_code,
				 self.city,
				 self.country,
			]
	   )

choshop/markers/views.py
from django.shortcuts import render, reverse_lazy
from 
# Create your views here.
import json

from .models import Marker, Address
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.serializers import serialize
from django.views import generic


class MarkersMapView(generic.base.TemplateView):
	"""Markers map view."""

	template_name = "map.html"

	def get_context_data(self, **kwargs):
		"""Return the view context data."""
		context = super().get_context_data(**kwargs)
		context["markers"] = json.loads(serialize("geojson", Marker.objects.all()))
		return context

class AddressListView(LoginRequiredMixin, generic.ListView):
	model = Address
	template_name = 'address/address_list.html'

	def def get_queryset(self):
		return self.model.objects.filter(account=self.request.user)

class AddressCreateView(LoginRequiredMixin, generic.edit.CreateView):
	model = Address
	fields = [
		'name',
		'address1',
		'address2',
		'zip_code',
		'city', 
		'country'
	]
	success_url = reverse_lazy('address_list')
	template_name = 'address/address_form.html'

	def form_valid(self, form):
		obj = form.save(commit=False)
		obj.account = self.request.user
		obj.save()
		return super().form_valid(form)

class AddressUpdateView(LoginRequiredMixin, generic.edit.UpdateView):
	model = Address
	fields = [
		'name',
		'address1',
		'address2',
		'zip_code',
		'city', 
		'country'
	]
	template_name = 'address/address_update.html'

	success_url = reverse_lazy('address_list')
	
	def def get_queryset(self):
		return self.model.objects.filter(account=self.request.user)


class AddressDeleteView(LoginRequiredMixin, generic.edit.DeleteView):
	model = models.Address
    success_url = reverse_lazy("address_list")
	template_name = 'address/address_confirm_delete.html'
    def get_queryset(self):
        return self.model.objects.filter(user=self.request.user)

choshop/markers/templates/markers/address_confirm_delete.html
{% extends "shop/base.html" %}
{% block content %}
  <h2> حذف ادرس</h2>
  <form method="POST">
    {%  csrf_token %}
    <p>Aآیا اطمینان دارید که میخواهید ادرس را حذف کنید؟</p>
    <button type="submit" class="btn btn-danger">حذف</button>
  </form>
{% endblock content %}

choshop/markers/templates/markers/address_form.html
{% extends "shop/base.html" %}
{% block content %}
<h2>یک ادرس وارد کنید</h2>
<form method="POST">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit" class="btn btn-­primary">ثبت</button>
</form>
{% endblock content %}

choshop/markers/templates/markers/address_list.html
{% extends "shop/base.html" %}
{% block content %}
  <h1>آدرس های شما</h1>
  {% for address in object_list %}
    <p>
      {{ address.name }}<br>
      {{ address.address1 }}<br>
      {{ address.address2 }}<br>
      {{ address.city }}<br>
      {{ address.get_country_display }}<br>
    </p>
    <p>
      <a href="{% url "address_update" address.id %}"> تغییر آدرس</a>
    </p>
    <p>
       <a href="{% url "address_delete" address.id %}"> حذف آدرس </a>
    </p>
    {% if not forloop.last %}
      <hr>
    {% endif %}
  {% endfor %}
  <p>
    <a href="{% url "address_create" %}">اضافه کردن یک آدرس جدید</a>
  </p>
{% endblock con

choshop/markers/templates/markers/address_update.html
{% extends "shop/base.html" %}
{% block content %}
  <h2>اضافه کردن یک آدرس جدید</h2>
  <form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
     <button type="submit" class="btn btn-­primary">ثبت</button>
  </form>
{% endblock content %}