choshop/blog/urls.py
from django.urls import path
from . import views 
app_name = 'blog'
urlpatterns = [
	path('detail',views.detail ,name='post_detail'),
	path('list',views.list_posts ,name='list_posts'),

]

choshop/cart/urls.py
from django.urls import path
from . import views 

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>', views.cart_remove, name='cart_remove'),
]

choshop/choshop/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

from django.views.decorators.csrf import csrf_protect, csrf_exempt
from graphene_django.views import GraphQLView
urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    # added 
    path('account/', include('django.contrib.auth.urls')),
    path('blog/', include('blog.urls')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('', include('shop.urls')),
    path('orders', include('orders.urls')),
    path('markers', include('markers.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),

    path('graphql/', csrf_exempt(GraphQLView.as_view(graphiql=True))),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

choshop/shop/urls.py
from . import views 
from django.urls import path,include

app_name = 'shop'

urlpatterns = [
   path('product_detail/<int:id>/<slug:slug>',views.product_list, name='product_detail'),
   path('product_list/',views.product_detail, name='product_list'),
   path(
        "products/<slug:tag>/",
        views.ProductListView.as_view(),
        name="products",
    ),
    path('product/<slug:slug>', views.ProductDetailview.as_view(), name='product')
]

choshop/shop/models/product.py
from django.db import models
from django.conf import settings 
#from django.contrib.gis.db import models as gis_models 
from account.models import Account 
from .tag_product import ProductTag 
from .product_image import ProductImage
from .product_sub_tag import ProductSubTag 
from core.shared import Postable
from django.utils import timezone
from ckeditor_uploader.fields import RichTextUploadingField
# Storage 

from .storages import ProtectedStorage


from .shop import Shop


def get_storage_location():
	if settings.DEBUG:
		return ProtectedStorage()

class Product(Postable): 
	#STATUS_CHOICES = (
	#	('available', "موجود"),
	#	('out', 'ناموجود')
	#)
	name = models.CharField(default='ghups', max_length=50,verbose_name='نام محصول ')
	
	description = RichTextUploadingField(verbose_name='توضیحات')
	
	available = models.BooleanField(default=True,verbose_name='موجوده')
	
	numbers = models.PositiveSmallIntegerField(verbose_name='تعداد محصول')

	is_finishing = models.BooleanField(verbose_name='آیا محصول در آستانه به پایان رسیدن است؟', default=False)

	tags = models.ManyToManyField(ProductTag,verbose_name='تگ')	

	sub_tags = models.ManyToManyField(ProductSubTag,verbose_name='زیر تگ')

	for_the_shop = models.ForeignKey(Shop, on_delete=models.CASCADE,verbose_name='برای فروشگاهه')

	price = models.DecimalField(max_digits=10, decimal_places=2,verbose_name='قیمت')
	
	image = models.ForeignKey(ProductImage, on_delete=True)

	video_link = models.URLField(blank=True, null=True ,verbose_name='لینک ویدیو')
	
	media = models.FileField(storage=ProtectedStorage, upload_to='products/', null=True, blank=True,verbose_name='فایل غیره')
	
	is_bestseller = models.BooleanField(default=False,verbose_name='بهترین فروش رو داشته؟')
	
	old_price = models.DecimalField(max_digits=9,decimal_places=2, blank=True,default=0.00,verbose_name='قیمت قدیمی')
	
	sku = models.CharField(max_length=50 ,verbose_name='شناسه اصلی ')
	
	requires_shipping = models.BooleanField(default=False,verbose_name='آیا نیاز به جابجایی داره؟')
		
	can_backorder = models.BooleanField(default=False,verbose_name='آیا پس گرفته میشه؟')
	
	@property
	def can_order(self):
		if self.has_inventory():
			return True
		elif self.can_backorder:
			return True
		return False
	
	@property
	def order_btn_title(self):
		if self.can_order and not self.has_inventory():
			return "Backorder"
		if not self.can_order:
			return "Cannot purchase."
		return "Purchase"

	def has_inventory(self):
		return self.numbers > 0 # True or False

	def remove_items_from_inventory(self, count=1, save=True):
		current_inv = self.numbers
		current_inv -= count
		self.numbers = current_inv
		if save == True:
			self.save()
		return self.numbers	

choshop/shop/models/product_image.py
from django.db import models 
from . import Product



class ProductImage(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)

    image = models.ImageField(upload_type='product-images')

    thumbnail = models.ImageField(upload_to='product-thumbnails', null=True)

    

choshop/shop/models/product_sub_category.py
from django.db import models
from django.urls import reverse
from core.shared import Postable
from .product_category import Category

class SubCategory(Postable):
	
	name = models.CharField(max_length=50,verbose_name='نام زیر تگ')

	cat = models.ForeignKey(Category, on_delete=models.CASCADE,verbose_name='نام تگ اصلی ')


	def __str__(self):
		return f'{self.name} in {self.cat}' 

	class Meta:
		ordering = ('name', )
		verbose_name ='زیرتگ '
		verbose_name_plural = 'زیرتگ ها '

choshop/shop/models/product_sub_tag.py
from django.db import models
from django.urls import reverse
from core.shared import Postable
from .product import Product 
from .tag_product import ProductTag
from shop.managers import ProductCategoryManager

class ProductSubTag(Postable):
	
	name = models.CharField(max_length=50,verbose_name='نام زیر تگ')

	cat = models.ForeignKey(ProductTag, on_delete=models.CASCADE,verbose_name='نام تگ اصلی ')

	products = models.ManyToManyField(Product, blank=True) 
	
	objects = ProductCategoryManager()

	def __str__(self):
		return f'{self.name} in {self.cat}' 

	class Meta:
		ordering = ('name', )
		verbose_name ='زیرتگ '
		verbose_name_plural = 'زیرتگ ها '

choshop/shop/models/product_tag.py
from django.db import models
from django.urls import reverse
from core.shared import Postable
from .product import Product

from shop.managers import ProductCategoryManager
'''
Django offers a special type of field called ManyToManyField, which
automatically creates a linking table between two tables, in this case Product
Tags and Products. This linking table allows you to create relationships
where any tags can be associated to any products and vice versa.
'''

class ProductTag(Postable):
	
	name = models.CharField(max_length=50,verbose_name='نام تگ')

	products = models.ManyToManyField(Product, blank=True) 
	
	
	objects = ProductCategoryManager()

	def __str__(self):
		return self.name 

	def natural_key(self):
		return (self.slug,)
	
	class Meta:
		ordering = ('name', )
		verbose_name = 'تگ'
		verbose_name_plural = 'تگ ها '

choshop/shop/models/shop.py
from django.db import models
#from django.contrib.gis.db import models as gis_models 
from account.models import Account
from .tag_product import ProductTag 
from .product_sub_tag import ProductSubTag 
#from .product import Product
from core.shared import Postable
from django.utils import timezone
from ckeditor_uploader.fields import RichTextUploadingField

class Shop(models.Model):
	name = models.CharField(default= 'ChoShop', max_length=50, verbose_name='نام فروشگاه')
	
	#loc = models.OneToOneField(Location, on_delete=models.SET_NULL, null=True)
	
	#shopper = models.OneToOneField(Shopper, on_delete=models.CASCADE)
	
	#products = models.ForeignKey(Product,on_delete=models.CASCADE )

	def __str__(self):
		return f'{self.name} with the ownership of {self.shpper.email}'

choshop/shop/models/storages.py
from django.conf import settings
from django.core.files.storage import FileSystemStorage
from django.core.exceptions import ImproperlyConfigured


PROTECTED_MEDIA = getattr(settings, 'PROTECTED_MEDIA', None)
if PROTECTED_MEDIA == None:
    raise ImproperlyConfigured("PROTECTED_MEDIA is not set in settings.py")

# django-storages
class ProtectedStorage(FileSystemStorage):
    location = PROTECTED_MEDIA # MEDIA_ROOT

choshop/shop/models/tag_product.py
from django.db import models
from django.urls import reverse
from core.shared import Postable
#from .product import Product

from shop.managers import ProductCategoryManager
'''
Django offers a special type of field called ManyToManyField, which
automatically creates a linking table between two tables, in this case Product
Tags and Products. This linking table allows you to create relationships
where any tags can be associated to any products and vice versa.
'''

class ProductTag(Postable):
	
	name = models.CharField(max_length=50,verbose_name='نام تگ')

	#products = models.ManyToManyField(Product, blank=True) 
	
	
	objects = ProductCategoryManager()

	def __str__(self):
		return self.name 

	def natural_key(self):
		return (self.slug,)
	
	class Meta:
		ordering = ('name', )
		verbose_name = 'تگ'
		verbose_name_plural = 'تگ ها '

choshop/shop/views.py
from django.shortcuts import render, get_object_or_404, redirect
from . import models 
# Create your views here.
from cart.forms import CartAddProductForm
from django.views import generic 



def product_detail(request, id, slug):
    product = get_object_or_404(models.Product, id=id, slug=slug, available=True)

    cart_product_form = CartAddProductForm()
    return render(request, 'shop/product/detail.html', {'product':product, 'cart_product_form':cart_product_form})


def product_list(request):
    return render(request, 'shop/product/list.html', {'products':models.Product.objects.all()})

class ProductListView(generic.ListView):
    template_name = 'shop/product/class-list.html'
    paginate_by = 4
    
    def get_queryset(self):
        tag = self.kwargs['tag']
        self.tag = None 
        if tag != 'all':
            self.tag = get_object_or_404(models.ProductTag, slug=tag)
        
        if self.tag:
            products = models.Product.objects.active().filter(tags=self.tag)
        
        else:
            products = models.Product.objects.active()
        return products.order_by("name")
'''
'Another thing worth mentioning in the template is how related models
are traversed. If a model has a foreign key to another table, it is possible to
call the methods of the related managers by just specifying their names.
object.tags.all in templates, for example, is equivalent to object.tags.
all() in Python.'''


class ProductDetailview(generic.DetailView):
    model = models.Product
    template_name = 'shop/product/class-detail.html'

choshop/shop/templates/shop/product/class-detail.html
{% extends "shop/base.html" %} {% block content %}
<h1>محصولات</h1>
<table class="table">
    <tr>
        <th>نام</th>
        <td>{{ object.name }}</td>
    </tr>
    <tr>
        <th>عکس</th>
        <td>
            <div id='imagebox'>
                Loading...
            </div>
        </td>
    </tr>
    <tr>
        <th>فیمت</th>
        <td>{{ object.price }}</td>
    </tr>
    <tr>
        <th>توضیحات</th>
        <td>{{ object.description|linebreaks }}</td>
    </tr>
    <tr>
        <th>تگ ها</th>
        
        <td>{{ object.tags.all|join:","|default:"No tags available" }}</td>
    </tr>
    <tr>
        <th>اپدیت در</th>
        <td>{{ object.date_updated|date:"F Y" }}</td>
    </tr>
</table>
 <a href="{% url " add_to_basket " %}?product_id={{ object.id }}">
اضافه به سبد خرید </a> {% endblock content %} {% block js %}
<script src='https://unpkg.com/react@16/umd/react.production.min.js'></script>
<script src="https://unpkg.com/react-dom@16/umd/react-dom.production.min.js"></script>
<style type='text/css' media='screen'>
    .image {
        margin: 10px;
        display: inline-block;
    }
</style>
<script>
    const e = React.createElement;
    class ImageBox extends React.Component {
        constructor(props) {
            super(props);
            this.state = {
                currentImage: this.props.imageStart
            }
        }

        click(image) {
            this.setState({
                currentImage: image
            });
        }

        render() {
            const images = this.props.images.map((i) =>
                e('div', {
                        className: "image",
                        key: i.id
                    },
                    e('img', {
                        onClick: this.click.bind(this, i),
                        width: "100",
                        src: i.thumbnail
                    }),
                ),
            );
            return e('div', {
                    className: "gallery"
                },
                e('div', {
                        className: "current-image"
                    },
                    e('img', {
                        src: this.state.currentImage.image
                    })
                ),
                images)
        }
    }
    document.addEventListener("DOMContentLoaded",
        function(event) {
            var images = [
            {% for image in object.productimage_set.all %}
             {"image": "{{ image.image.url|safe }}",
              "thumbnail": "{{ image.thumbnail.url|safe }}"},
            { % endfor %}
            ]
            ReactDOM.render(
                e(ImageBox, {
                    images: images,
                    imageStart: images[0]
                }),
                document.getElementById('imagebox')
    );
  });
</script>
{% endblock %}

choshop/shop/templates/shop/product/class-list.html
{% extends "shop/base.html" %}
{% block content %}
  <h1>محصولات</h1>
  {% for product in page_obj %}
    <p>{{ product.name }}</p>
    <p>
      <a href="{% url "product" product.slug %}">اینحارو ببینید</a>
    </p>
    {% if not forloop.last %}
      <hr>
    {% endif %}
  {% endfor %}
  <nav>
    <ul class="pagination">
      {% if page_obj.has_previous %}
        <li class="page-item">
          <a
            class="page-link"
            href="?page={{page_obj.previous_page_number}}">
قبلی</a>
        </li>
      {% else %}
        <li class="page-item disabled">
          <a class="page-link" href="#">قبلی</a>
        </li>
      {% endif %}
      {% for pagenum in page_obj.paginator.page_range %}

        <li
          class="page-item{% if page_obj.number == pagenum %}
active{% endif %}">
           <a class="page-link" href="?page={{pagenum}}">{{pagenum}}
</a>
        </li>
      {% endfor %}
      {% if page_obj.has_next %}
        <li class="page-item">
           <a class="page-link" href="?page={{page_obj.next_
page_number}}">بعدی</a>
        </li>
      {% else %}
        <li class="page-item disabled">
          <a class="page-link" href="#">بعدی</a>
        </li>
      {% endif %}
    </ul>
  </nav>
{% endblock content %}

choshop/shop/templates/shop/product/detail.html
{% extends '../base.html' %}
{% block content %}
<p class='price'>${{ product.price }}</p>


<form action='{% url "cart:cart_add" product.id %}' method="post">
    {% csrf_token %}

    {{ cart_product_form }}
    <input type="submit" value="اضافه به سبد خرید ">
</form>
{{ product.description|linebreaks }}
{% endblock %}