choshop/blog/urls.py
from django.urls import path
from . import views 
app_name = 'blog'
urlpatterns = [
	path('detail',views.detail ,name='post_detail'),
	path('list',views.list_posts ,name='list_posts'),

]

choshop/cart/urls.py
from django.urls import path
from . import views 

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>', views.cart_remove, name='cart_remove'),
]

choshop/choshop/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

from django.views.decorators.csrf import csrf_protect, csrf_exempt
from graphene_django.views import GraphQLView
urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    # added 
    path('account/', include('django.contrib.auth.urls')),
    path('blog/', include('blog.urls')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('', include('shop.urls')),
    path('orders', include('orders.urls')),
    path('markers', include('markers.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),

    path('graphql/', csrf_exempt(GraphQLView.as_view(graphiql=True))),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

choshop/shop/urls.py
from . import views 
from django.urls import path,include

app_name = 'shop'

urlpatterns = [
   path('product_detail/<int:id>/<slug:slug>',views.product_list, name='product_detail'),
   path('product_list/',views.product_detail, name='product_list'),
   path(
        "products/<slug:tag>/",
        views.ProductListView.as_view(),
        name="products",
    ),
    path('product/<slug:slug>', views.ProductDetailview.as_view(), name='product')
]

choshop/cart/models.py
from django.db import models

# Create your models here.

choshop/cart/forms.py
from django import forms 
PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1,21)]

class CartAddProductForm(forms.Form):
    # This allows the user to select a quantity between one and 20. You
    #use a TypedChoiceField field with coerce=int to convert the input into an integer.
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)


    override = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

    '''
    This allows you to indicate whether the quantity has to be added
    to any existing quantity in the cart for this product ( False ), or whether the
    existing quantity has to be overridden with the given quantity ( True ). You
    use a HiddenInput widget for this field, since you don't want to display it
    to the user.'''

choshop/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from .cart import Cart 
from .forms import CartAddProductForm
from shop.models import Product 
# Create your views here.
# You use the require_POST decorator to allow only POST requests
@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST) 
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product, quantity=cd['quantity'], override_quantity=cd['override'])

    return redirect('cart:cart_detail')

@require_POST
def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')

'''
You create an instance of CartAddProductForm for each item in the cart to allow
changing product quantities. You initialize the form with the current item quantity
and set the override field to True so that when you submit the form to the cart_
add view, the current quantity is replaced with the new one.
'''

def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={
            'quantity': item['quantity'],
            'override': True,
        })
    return render(request, 'cart/detail.html', {'cart':cart})

choshop/cart/templates/cart/detail.html
{% extends "shop/base.html" %}
{% load static %}
{% block title %}
	Your shopping cart
{% endblock %}
{% block content %}
<h1>سبد خرید شما </h1>
<table class="cart">
	<thead>
		<tr>
			<th>Image</th>
			<th>Product</th>
			<th>Quantity</th>
			<th>Remove</th>
			<th>Unit price</th>
			<th>Price</th>
		</tr>
	</thead>
<tbody>
	{% for item in cart %}
		{% with product=item.product %}
			<tr>
				<td>
					<a href="{{ product.get_absolute_url }}">
					<img src="{% if product.image %}{{ product.image.url
					}}
					{% else %}{% static "img/no_image.png" %}{% endif %}">
					</a>
				</td>
				<td>{{ product.name }}</td>
				<td>
					<form action='{% url "cart:cart_add" product.id %}' method='post'>
						{{ item.update_quantity_form.quantity }}
						{{ item.update_quantity_form.override }}
						<input type='submit' value='تغییر؟' class='btn btn-info'> 
						{% csrf_token %}
					</form>
				</td>
				<td>
					<form action="{% url "cart:cart_remove" product.id %}"
					method="post">
					<input type="submit" value="پاک کردن">
					{% csrf_token %}
					</form>
				</td>
				<td class="num">${{ item.price }}</td>
				<td class="num">${{ item.total_price }}</td>
			</tr>
		{% endwith %}
	{% endfor %}
	<tr class="total">
		<td>مجموع</td>
		<td colspan="4"></td>
		<td class="num">${{ cart.get_total_price }}</td>
	</tr>
</tbody>
</table>
<p class="text-right">
<a href="{% url "shop:product_list" %}" class="button
light">ادامه خرید </a>
<a href="#" class="button">پرداخت؟</a>
</p>
{% endblock %}